### ISSUE TITLE
SCARED dataset

### ISSUE THREAD

**Issue by Miaowei-HNU** [dimitrisPs/scared_toolkit#1]
Can you share the data set? There are no more data sets on the official organizing committee. Please!

**Comment by dimitrisPs** [comment]
Hello, apologies for the late response. The dataset is more than 100 GB in size and, unfortunately, I do not have a way of hosting it in the cloud. I know that recently others got access to the SCARED dataset by contacting the challenge organizers. you can find their contact information on the [SCARED challenge webpage](https://endovissub2019-scared.grand-challenge.org/).

**Comment by Miaowei-HNU** [comment]
Thanks
















At 2022-08-30 17:24:27, "Dimitrios Psychogyios" ***@***.***> wrote:

Hello, apologies for the late response. The dataset is more than 100 GB in size and, unfortunately, I do not have a way of hosting it in the cloud. I know that recently others got access to the SCARED dataset by contacting the challenge organizers. you can find their contact information on the SCARED challenge webpage.
